general:
  app_name: risknet
  log_bucket: gs://albell-logs/
  dask_cluster_type: local
  gcp_dask_workers: 4
data:
  titanic_root: gs://albell-test/
  #change to local path
  fm_root : src/risknet/data/
  files:
    - !!python/tuple ['monthly.parquet', 'dev_labels.parquet', 'dev_reg_labels.parquet']
model:
  cv_strategy: time-series
  imputation: zero
  selection: RFE
  exclude_features: [A, B, C, D]
