# COPY EVERYTHING BELOW INTO conf.yaml (Create if doesn't exist)
general:
  app_name: risknet
  log_bucket: gs://albell-logs/
  dask_cluster_type: local
  gcp_dask_workers: 4
data:
  titanic_root: gs://albell-test/
  fm_root : "INSERT_DATA_HERE" #TODO: Add your fm_root
  files:  
    - !!python/tuple ['historical_data_time_2009Q1.txt', 'dev_labels.pkl', 'dev_reg_labels.pkl'] #File names for getting the data
    #TODO modify file names as needed
model:
  cv_strategy: time-series
  imputation: zero
  selection: RFE
  exclude_features: [A, B, C, D]

